import { getPackageVersion } from "./cli-version.mjs";

export function formatQuickHelp(version = getPackageVersion()) {
  return [
    `AgentX ${version}`,
    "Usage: agentx [flags] [message...]",
    "",
    "Chat:",
    "  normal text  send a message to OpenAI",
    "  agentx 'message'  send once, print summary, then exit",
    "  cd <path>    change the local working directory",
    "  !command     run a local shell command",
    "",
    "Commands:",
    "  clear        reset the saved session",
    "  !clear       clear the terminal",
    "  /usage       show token and cost totals",
    "  /goal TEXT   work autonomously toward a goal",
    "  /goal status show active goal status",
    "  /goal cancel cancel the active goal",
    "  /stop        cancel the active goal",
    "  /setup       edit settings and reload them",
    "  quit/exit    leave AgentX",
    "",
    "Flags:",
    "  --help, -h, -?   show this help",
    "  --version, -v    print the package version",
    "  --debug          print raw websocket logs and suppress live status lines",
    "  --cwd PATH, -C PATH  use PATH as the working directory",
    "  --check-mcp, -K  validate MCP config without contacting APIs",
    "  --confirm        enable tool confirmation prompts",
    "  --yolo           legacy alias; bypass tool confirmation prompts",
    "  --quiet, -q      suppress usage, timers, and tool/status output (keeps reasoning)",
    "  --no-usage, -u   suppress usage output",
    "  --no-colors, -c  suppress ANSI colors",
    "  --no-timers, -t  suppress status timer output",
    "  --no-reasoning, -r  suppress reasoning output",
    "  --no-shell-calls, -s  suppress shell-call output",
    "  --no-tool-calls, -o  suppress non-shell tool-call output",
    "  --no-mcp, -m     disable MCP tool loading",
    "  --no-mcp-output, -M  suppress MCP output while keeping MCP enabled",
    "  --no-websearch, -w  suppress web-search output",
    "  Short output flags may be stacked, for example: -qur",
  ].join("\n");
}
